name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v2
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.PF_APPLEDEV_SIGNCERT }}
          P12_PASSWORD: ${{ secrets.PF_APPLEDEV_SIGNCERT_PWD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.PF_APPLEDEV_PROVISION }}
          KEYCHAIN_PASSWORD: ${{ secrets.RUNNER_KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
      - name: Pod Install
        run: |
          pod repo update
          pod install
      - name: Build
        run: xcodebuild ARCHS=$(ARCHS_STANDARD) ONLY_ACTIVE_ARCH=NO -configuration Debug -workspace PartsFinder.xcworkspace -scheme PartsFinder
